export type TagVariant =
  | "three"
  | "websockets"
  | "react"
  | "redis"
  | "gray"
  | "html"
  | "css"
  | "javascript"
  | "node"
  | "next"
  | "kubernetes"
  | "postgresql"
  | "ogl"
  | "glsl"
  | "python"
  | "docker"
  | "fastapi"
  | "security"
  | "automation"
  | "n8n"
  | "api"
  | "rag"
  | "localai"
  | "llm"
  | "orchestration"
  | "python-pptx"
  | "ffmpeg"
  | "gemini"
  | "gemma"
  | "workflows"
  | "soc"
  | "migration"
  | "electron"
  | "vite"
  | "typescript"
  | "tailwind"
  | "cpp"
  | "qt"
  | "express"
  | "go"
  | "nocodb"
  | "flask"
  | "nginx"
  | "rabbitmq";

export const tagLabels = {
  three: "Three.js",
  websockets: "WebSockets",
  react: "React",
  redis: "Redis",
  gray: "Gray",
  html: "HTML",
  css: "CSS",
  javascript: "JavaScript",
  node: "Node.js",
  next: "Next.js",
  kubernetes: "Kubernetes",
  postgresql: "PostgreSQL",
  ogl: "OGL.js",
  glsl: "GLSL",
  python: "Python",
  docker: "Docker",
  fastapi: "FastAPI",
  security: "Security",
  automation: "Automation",
  n8n: "n8n",
  api: "API",
  rag: "RAG",
  localai: "LocalAI",
  llm: "LLM",
  orchestration: "Orchestration",
  "python-pptx": "python-pptx",
  ffmpeg: "FFmpeg",
  gemini: "Gemini",
  gemma: "Gemma",
  workflows: "Workflows",
  soc: "SOC",
  migration: "Migration",
  electron: "Electron",
  vite: "Vite",
  typescript: "TypeScript",
  tailwind: "TailwindCSS",
  cpp: "C++",
  qt: "Qt",
  express: "Express",
  go: "Go",
  nocodb: "NocoDB",
  flask: "Flask",
  nginx: "Nginx",
  rabbitmq: "RabbitMQ",
} as const satisfies Record<TagVariant, string>;
